---
stages:
  - test
  - release

test:
  image: isic/isic-challenge-scoring-test:latest
  stage: test
  script:
    - tox

release:
  image: isic/isic-challenge-scoring-test:latest
  stage: release
  script:
    - tox -e release
  only:
    - master
