---
version: 2.1
jobs:
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - run:
          name: Install Git LFS
          command: |
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
            sudo apt-get install git-lfs
      - checkout
      - run:
          name: Install tox
          command: sudo pip install tox
      - run:
          name: Run linting tests
          command: tox -e lint
      - run:
          name: Run type checking tests
          command: tox -e type
      - run:
          name: Run pytest tests
          command: tox -e test -- --junitxml=./test_results/junit.xml
      - store_test_results:
          path: ./test_results
  release:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install tox
          command: sudo pip install tox
      - deploy:
          name: Publish release
          command: tox -e release
workflows:
  version: 2
  ci:
    jobs:
      - test:
          filters:
            # Tags must be explicitly run, and the "release" job requires this
            tags:
              only: /.*/
      - release:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
