---
version: 2.1
jobs:
  test:
    docker:
      - image: isic/isic-challenge-scoring-test:latest
    steps:
      - checkout
      - run:
          name: Run tests
          command: tox
  release:
    docker:
      - image: isic/isic-challenge-scoring-test:latest
    steps:
      - checkout
      - run:
          name: Publish release
          command: tox -e release
workflows:
  version: 2
  build:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
